name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/systemcore-cross-ubuntu:2027-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build robot code
        run: ./gradlew build
