java_binary(
    name = "maven-zip-publisher",
    srcs = ["MavenZipPublisher.java"],
    #javacopts = [
    #    "-source",
    #    "8",
    #    "-target",
    #    "8",
    #],
    main_class = "MavenZipPublisher",
    visibility = ["//visibility:public"],
)
