cc_library(
    name = "wpilibio-athena",
    srcs = glob(["src/**/*.cc"]),
    hdrs = glob(["include/**/*.h"]),
    deps = ["//conduit:conduit-schema-cc", "//conduit/api:api-jni-athena", "//third_party/wpilib:hal-athena"]
)
