load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "core",
    srcs = glob(["src/**/*.java"]),
    deps = [
        "//conduit/api",
        "//third_party/wpilib:wpilibj",
    ],
)
